const quotes = [
  "Believe in yourself and keep moving forward.",
  "Success begins with a single step.",
  "Dream big, work hard, stay humble.",
  "Small progress is still progress.",
  "Discipline beats motivation every day.",
  "Your only limit is your mindset.",
  "Consistency creates extraordinary results.",
  "Every challenge is an opportunity to grow.",
  "Great things take time and patience.",
  "Stay focused on your goals.",
  "Failure is a lesson, not the end.",
  "Hard work always leaves a mark.",
  "Confidence comes from preparation.",
  "Learn something new every day.",
  "Don't wait for opportunity, create it.",
  "Mistakes are proof you're trying.",
  "Believe you can, and you're halfway there.",
  "Success is earned, not given.",
  "Your future depends on today's actions.",
  "Never stop improving yourself.",
  "Push yourself beyond your comfort zone.",
  "Stay curious and keep learning.",
  "Every expert was once a beginner.",
  "Progress over perfection.",
  "Keep going even when it's hard.",
  "Action is the foundation of success.",
  "A positive mindset changes everything.",
  "Patience is a powerful skill.",
  "Your effort determines your outcome.",
  "Be stronger than your excuses.",
  "The best investment is in yourself.",
  "Focus on solutions, not problems.",
  "Success loves consistency.",
  "Do today what others won't.",
  "Kindness is always a strength.",
  "Make each day count.",
  "Turn obstacles into opportunities.",
  "Keep your goals bigger than your fears.",
  "Success starts with self-belief.",
  "Stay determined, stay unstoppable.",
  "Good things happen to those who persist.",
  "Growth begins at the edge of comfort.",
  "Every day is a fresh beginning.",
  "Be fearless in the pursuit of your dreams.",
  "Your attitude shapes your future.",
  "Stay patient and trust the process.",
  "Winners never stop learning.",
  "One step at a time is enough.",
  "The journey matters as much as the destination.",
  "Never underestimate the power of persistence."
];

const h3 = document.querySelector("h3")
const btn = document.getElementById("btn") 

btn.addEventListener('click',()=>{
  h3.textContent = `${quotes[Math.floor(Math.random()*50)]}`
})